# Generated by Django 4.1.3 on 2022-11-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_user_cart_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='email',
            new_name='user',
        ),
    ]
