# Generated by Django 4.1.3 on 2022-11-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_email_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
