# Generated by Django 4.1.3 on 2022-12-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_applied',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
