# Generated by Django 4.1.3 on 2022-12-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
