# Generated by Django 4.1.3 on 2022-12-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount_discounted',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
