# Generated by Django 4.1.3 on 2022-12-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_amount_discounted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='coupon_discount',
            new_name='discount_percentage',
        ),
    ]
