# Generated by Django 4.1.4 on 2023-01-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0079_productattribute_product"),
        ("cart", "0010_rename_coupon_discount_cart_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product_attr",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.productattribute",
            ),
        ),
    ]
