# Generated by Django 4.1.4 on 2023-01-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_alter_cart_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
    ]
