# Generated by Django 4.1.4 on 2023-04-14 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0091_remove_products_color_remove_products_condition"),
        ("cart", "0013_remove_cart_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product_attr",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.products",
            ),
        ),
    ]
