# Generated by Django 4.1.4 on 2023-04-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0014_alter_cart_product_attr"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
