# Generated by Django 4.1.4 on 2023-04-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0118_alter_categories_options_products"),
        ("cart", "0015_delete_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=255, null=True)),
                ("product_qty", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "coupon_applied",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("discount_percentage", models.FloatField(blank=True, null=True)),
                ("amount_discounted", models.FloatField(blank=True, null=True)),
                ("grand_total", models.FloatField(blank=True, null=True)),
                (
                    "product_attr",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.products",
                    ),
                ),
            ],
        ),
    ]
