# Generated by Django 4.1.4 on 2023-04-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0132_alter_product_color_color_price"),
        ("cart", "0016_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="color_selected",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color_added",
                to="category.product_color",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="varaint_selected",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_added",
                to="category.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="product_attr",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_added",
                to="category.products",
            ),
        ),
    ]
