# Generated by Django 4.1.4 on 2023-04-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0017_cart_color_selected_cart_varaint_selected_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="varaint_selected",
            new_name="variant_selected",
        ),
    ]
