# Generated by Django 4.1.4 on 2023-04-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0133_products_second_image_products_third_image_and_more"),
        ("cart", "0018_rename_varaint_selected_cart_variant_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="variant_color_selected",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variantColor",
                to="category.variantcolor",
            ),
        ),
    ]
