# Generated by Django 4.1.4 on 2023-04-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0133_products_second_image_products_third_image_and_more"),
        ("cart", "0019_cart_variant_color_selected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="color_selected",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color_added",
                to="category.product_color",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="product_attr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_added",
                to="category.products",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="variant_color_selected",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variantColor",
                to="category.variantcolor",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="variant_selected",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_added",
                to="category.productvariant",
            ),
        ),
    ]
