# Generated by Django 4.1.4 on 2023-05-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
