# Generated by Django 4.1.1 on 2022-11-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
