# Generated by Django 4.1.4 on 2023-04-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_orderitem_variantcolor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
