# Generated by Django 4.1.1 on 2022-11-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_products_options_remove_products_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
