# Generated by Django 4.1.1 on 2022-11-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_products_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
