# Generated by Django 4.1.1 on 2022-11-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='condition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
