# Generated by Django 4.1.4 on 2023-05-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0007_rename_product_name_wishlist_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="wishlist_name",
        ),
    ]
