# Generated by Django 4.1.3 on 2022-11-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_products_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='generation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
