# Generated by Django 4.1.3 on 2022-11-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_products_generation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_out_of_stock',
        ),
        migrations.AlterField(
            model_name='products',
            name='generation',
            field=models.IntegerField(blank=True),
        ),
    ]
