# Generated by Django 4.1.3 on 2022-11-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_remove_products_is_out_of_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='generation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
