# Generated by Django 4.1.3 on 2022-11-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_products_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories'),
        ),
    ]
