# Generated by Django 4.1.3 on 2022-11-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_remove_products_images_product_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Images',
        ),
    ]
