# Generated by Django 4.1.3 on 2022-11-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_delete_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
    ]
