# Generated by Django 4.1.3 on 2022-11-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_products_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='products',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
    ]
