# Generated by Django 4.1.3 on 2022-11-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_products_second_image_products_third_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='products',
            name='internal_storage',
        ),
        migrations.RemoveField(
            model_name='products',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='series',
        ),
        migrations.RemoveField(
            model_name='products',
            name='third_image',
        ),
    ]
