# Generated by Django 4.1.3 on 2022-11-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_producttype_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='processor',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
