# Generated by Django 4.1.3 on 2022-11-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_remove_products_brand_remove_products_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('generation', models.IntegerField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('internal_storage', models.CharField(default='32 GB', max_length=5)),
                ('price', models.IntegerField(default=1000)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='images/products')),
            ],
        ),
    ]
