# Generated by Django 4.1.3 on 2022-11-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_products_processor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
