# Generated by Django 4.1.3 on 2022-11-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='internal_storage',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='series',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='third_image',
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='generation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='internal_storage',
            field=models.CharField(default='32 GB', max_length=5),
        ),
        migrations.AddField(
            model_name='products',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='products',
            name='series',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
    ]
