# Generated by Django 4.1.3 on 2022-11-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0021_alter_products_camera_alter_products_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='battery',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
