# Generated by Django 4.1.3 on 2022-11-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0021_remove_products_category_delete_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='images/products')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
