# Generated by Django 4.1.3 on 2022-11-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0022_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
