# Generated by Django 4.1.3 on 2022-11-27 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0022_alter_products_battery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('address_line1', models.TextField(max_length=200, null=True)),
                ('address_line2', models.TextField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('payment_mode', models.CharField(max_length=150, null=True)),
                ('payment_id', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Awaiting Payment', 'Awaiting Payment'), ('Out for Delivery', 'Out for Delivery')], default='Order Placed', max_length=150)),
                ('message', models.TextField(null=True)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
