# Generated by Django 4.1.3 on 2022-11-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0024_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
