# Generated by Django 4.1.3 on 2022-11-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0025_subcategory_products_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_SubCategory',
            fields=[
                ('sub_sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('generation', models.IntegerField()),
                ('series', models.CharField(blank=True, max_length=50)),
                ('ram', models.IntegerField()),
                ('internal_memory', models.IntegerField()),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_of_display', models.CharField(blank=True, max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('camera', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Sub-Sub-Categories',
            },
        ),
    ]
