# Generated by Django 4.1.3 on 2022-11-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0026_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
