# Generated by Django 4.1.3 on 2022-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0027_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Pending', 'Pending'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Completed', 'Completed'), ('Awaiting Payment', 'Awaiting Payment'), ('Out for Delivery', 'Out for Delivery'), ('Cancelled', 'Cancelled')], default='Order Placed', max_length=150),
        ),
    ]
