# Generated by Django 4.1.3 on 2022-11-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0028_remove_products_generation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_subcategory',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='sub_subcategory',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='sub_subcategory',
            name='internal_memory',
        ),
        migrations.RemoveField(
            model_name='sub_subcategory',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='sub_subcategory',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='sub_subcategory',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='sub_subcategory',
            name='series',
        ),
        migrations.RemoveField(
            model_name='sub_subcategory',
            name='type_of_display',
        ),
    ]
