# Generated by Django 4.1.3 on 2022-11-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0029_remove_sub_subcategory_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='camera_spec',
            field=models.IntegerField(blank=True, default=12),
        ),
        migrations.AddField(
            model_name='products',
            name='generation',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='products',
            name='internal_memory',
            field=models.IntegerField(blank=True, default=32),
        ),
        migrations.AddField(
            model_name='products',
            name='processor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='ram',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name='products',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='series',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='type_of_display',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
