# Generated by Django 4.1.3 on 2022-11-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0030_products_camera_spec_products_generation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_SubCategory',
        ),
    ]
