# Generated by Django 4.1.3 on 2022-11-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0030_order_coupon_amount_order_ship_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_before_tax',
            field=models.FloatField(null=True),
        ),
    ]
