# Generated by Django 4.1.3 on 2022-11-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0031_delete_sub_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='camera_spec',
        ),
        migrations.RemoveField(
            model_name='products',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='products',
            name='internal_memory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='products',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='products',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='products',
            name='series',
        ),
        migrations.RemoveField(
            model_name='products',
            name='type_of_display',
        ),
    ]
