# Generated by Django 4.1.3 on 2022-12-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0031_order_price_before_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
