# Generated by Django 4.1.3 on 2022-11-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0032_remove_products_camera_spec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_type',
            field=models.CharField(default='Phones', max_length=50, unique=True),
        ),
    ]
