# Generated by Django 4.1.3 on 2022-11-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0033_remove_products_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='product_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
