# Generated by Django 4.1.3 on 2022-12-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0033_alter_orderitem_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('Cancel Order', 'Cancel Order'), ('Return', 'Return')], default='Order Placed', max_length=50),
        ),
    ]
