# Generated by Django 4.1.3 on 2022-12-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0036_alter_orderitem_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_line2',
        ),
    ]
