# Generated by Django 4.1.3 on 2022-11-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0036_products_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(default=11)),
                ('series', models.CharField(blank=True, max_length=50)),
                ('ram', models.IntegerField(blank=True, default=4)),
                ('internal_memory', models.IntegerField(blank=True, default=32)),
                ('screen_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('type_of_display', models.CharField(blank=True, max_length=100)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('camera_spec', models.IntegerField(blank=True, default=12)),
            ],
            options={
                'verbose_name_plural': 'Product Specifications',
            },
        ),
    ]
