# Generated by Django 4.1.3 on 2022-11-19 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0037_product_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.product_spec'),
        ),
    ]
