# Generated by Django 4.1.3 on 2022-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0038_alter_order_status_alter_orderitem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
