# Generated by Django 4.1.3 on 2022-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0039_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
