# Generated by Django 4.1.3 on 2022-12-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0040_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
