# Generated by Django 4.1.3 on 2022-11-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0041_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
