# Generated by Django 4.1.3 on 2022-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0042_remove_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/subcategory'),
        ),
    ]
