# Generated by Django 4.1.3 on 2022-12-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0042_products_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=100)),
                ('is_expired', models.BooleanField(default=True)),
                ('discount_percentage', models.IntegerField()),
                ('minimum_amount', models.IntegerField()),
            ],
        ),
    ]
