# Generated by Django 4.1.3 on 2022-11-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0043_subcategory_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Used', 'Used'), ('New', 'New'), ('Refurbished', 'Refurbished')], default='New', max_length=20),
        ),
    ]
