# Generated by Django 4.1.3 on 2022-11-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0044_alter_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_type',
        ),
    ]
