# Generated by Django 4.1.3 on 2022-11-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0045_remove_category_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='product_img',
        ),
    ]
