# Generated by Django 4.1.3 on 2022-12-14 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0045_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_till',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
