# Generated by Django 4.1.3 on 2022-11-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0046_remove_subcategory_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='products',
            name='generation',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product_Spec',
        ),
    ]
