# Generated by Django 4.1.3 on 2022-12-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0047_coupon_maximum_amount_coupon_tries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='tries',
        ),
    ]
