# Generated by Django 4.1.3 on 2022-11-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0048_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='condition',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
