# Generated by Django 4.1.3 on 2022-12-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0051_coupon_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='grand_total',
        ),
    ]
