# Generated by Django 4.1.3 on 2022-11-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0051_alter_subcategory_options_categories_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='sub_category',
            new_name='product_type',
        ),
    ]
