# Generated by Django 4.1.3 on 2022-11-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0052_rename_sub_category_categories_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
