# Generated by Django 4.1.3 on 2022-12-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0052_remove_coupon_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
