# Generated by Django 4.1.3 on 2022-11-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0053_delete_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
