# Generated by Django 4.1.3 on 2022-12-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0053_alter_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
