# Generated by Django 4.1.3 on 2022-11-21 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0055_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.categories'),
        ),
    ]
