# Generated by Django 4.1.3 on 2022-12-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0055_alter_coupon_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='offer_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
