# Generated by Django 4.1.3 on 2022-11-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0056_products_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('sub_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
    ]
