# Generated by Django 4.1.3 on 2022-12-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0057_products_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_after_offer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
