# Generated by Django 4.1.3 on 2022-11-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0059_categories_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='sub_cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/producttype'),
        ),
    ]
