# Generated by Django 4.1.3 on 2022-12-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0059_alter_products_color_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='applied_offer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
