# Generated by Django 4.1.3 on 2022-11-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0060_subcategories_sub_cat_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='sub_cat_image',
            new_name='product_type_image',
        ),
    ]
