# Generated by Django 4.1.3 on 2022-12-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0060_products_applied_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
