# Generated by Django 4.1.3 on 2022-11-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0061_rename_sub_cat_image_subcategories_product_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories'),
        ),
    ]
