# Generated by Django 4.1.3 on 2022-12-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0062_alter_wishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='user_id',
        ),
    ]
