# Generated by Django 4.1.3 on 2022-11-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0063_rename_subcategories_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='generation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='internal_storage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='series',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
