# Generated by Django 4.1.3 on 2022-12-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0064_rename_user_id_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Order Confirmed', max_length=50, null=True),
        ),
    ]
