# Generated by Django 4.1.3 on 2022-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0064_products_generation_products_internal_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='white', max_length=20),
        ),
    ]
