# Generated by Django 4.1.3 on 2022-12-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0065_alter_orderitem_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
    ]
