# Generated by Django 4.1.3 on 2022-11-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0065_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='camera',
            field=models.CharField(default='12 MP', max_length=100),
        ),
    ]
