# Generated by Django 4.1.3 on 2022-11-22 13:13

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0066_products_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('main_image', '400x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
