# Generated by Django 4.1.4 on 2022-12-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0067_remove_order_price_before_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order Confirmed", "Order Confirmed"),
                    ("Shipped", "Shipped"),
                    ("In Transit", "In Transit"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Order Confirmed",
                max_length=150,
            ),
        ),
    ]
