# Generated by Django 4.1.3 on 2022-11-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0068_remove_products_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
