# Generated by Django 4.1.4 on 2022-12-26 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("category", "0069_coupon_one_time_use"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("wallet_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.FloatField(blank=True, null=True)),
                (
                    "order_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="category.order"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
