# Generated by Django 4.1.4 on 2022-12-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0070_wallet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="order_number",
        ),
        migrations.AddField(
            model_name="wallet",
            name="orderItem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.orderitem",
            ),
        ),
    ]
