# Generated by Django 4.1.4 on 2022-12-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0071_remove_wallet_order_number_wallet_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
