# Generated by Django 4.1.4 on 2022-12-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0072_wallet_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
