# Generated by Django 4.1.4 on 2023-01-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0073_alter_order_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="applied_offer",
        ),
        migrations.RemoveField(
            model_name="products",
            name="color",
        ),
        migrations.RemoveField(
            model_name="products",
            name="price",
        ),
        migrations.RemoveField(
            model_name="products",
            name="price_after_offer",
        ),
        migrations.RemoveField(
            model_name="products",
            name="product_offer",
        ),
        migrations.RemoveField(
            model_name="products",
            name="quantity",
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField(default=0)),
                ("price", models.FloatField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.products",
                    ),
                ),
            ],
        ),
    ]
