# Generated by Django 4.1.4 on 2023-01-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "category",
            "0074_remove_products_applied_offer_remove_products_color_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
