# Generated by Django 4.1.4 on 2023-01-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0075_productattribute_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="main_image",
        ),
        migrations.RemoveField(
            model_name="products",
            name="second_image",
        ),
        migrations.RemoveField(
            model_name="products",
            name="third_image",
        ),
        migrations.AddField(
            model_name="productattribute",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/products"),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="second_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/products"),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="third_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/products"),
        ),
    ]
