# Generated by Django 4.1.4 on 2023-01-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0076_remove_products_main_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="color",
            field=models.CharField(default="black", max_length=100),
        ),
    ]
