# Generated by Django 4.1.4 on 2023-01-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0077_productattribute_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="product",
        ),
    ]
