# Generated by Django 4.1.4 on 2023-01-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0078_remove_productattribute_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.products",
            ),
        ),
    ]
