# Generated by Django 4.1.4 on 2023-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0079_productattribute_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productattribute",
            old_name="main_image",
            new_name="first_image",
        ),
        migrations.AddField(
            model_name="products",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/products"),
        ),
    ]
