# Generated by Django 4.1.4 on 2023-01-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0080_rename_main_image_productattribute_first_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.FloatField(default=100),
        ),
    ]
