# Generated by Django 4.1.4 on 2023-01-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0081_products_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="color",
            field=models.CharField(default="White", max_length=20),
        ),
    ]
