# Generated by Django 4.1.4 on 2023-01-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0083_alter_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="applied_offer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="price_after_offer",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="product_offer",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
