# Generated by Django 4.1.4 on 2023-01-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0084_productattribute_applied_offer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
