# Generated by Django 4.1.4 on 2023-01-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0085_productattribute_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("banner_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "banner_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "banner_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "banner_head",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "banner_link",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
        ),
    ]
