# Generated by Django 4.1.4 on 2023-01-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0086_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="productattribute",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
