# Generated by Django 4.1.4 on 2023-04-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0087_productattribute_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="size",
        ),
    ]
