# Generated by Django 4.1.4 on 2023-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0089_productattribute_product_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="product_size",
        ),
        migrations.AddField(
            model_name="productattribute",
            name="size",
            field=models.IntegerField(default=0),
        ),
    ]
