# Generated by Django 4.1.4 on 2023-04-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0090_remove_productattribute_product_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="color",
        ),
        migrations.RemoveField(
            model_name="products",
            name="condition",
        ),
    ]
