# Generated by Django 4.1.4 on 2023-04-14 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0014_alter_cart_product_attr"),
        ("category", "0091_remove_products_color_remove_products_condition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Sub_Variant",
            fields=[
                (
                    "pro_sub_variant_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("product_color", models.CharField(max_length=50)),
                ("pro_sub_variant_price", models.FloatField(default=100)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "product_variant_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("size", models.IntegerField(blank=True, null=True)),
                ("variant_price", models.FloatField(default=100)),
                ("slug", models.SlugField()),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.products",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="category.products"
            ),
        ),
        migrations.DeleteModel(
            name="ProductAttribute",
        ),
        migrations.AddField(
            model_name="product_sub_variant",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="category.productvariant",
            ),
        ),
    ]
