# Generated by Django 4.1.4 on 2023-04-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0092_product_sub_variant_productvariant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_sub_variant",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
