# Generated by Django 4.1.4 on 2023-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0093_product_sub_variant_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="is_featured",
        ),
        migrations.AddField(
            model_name="product_sub_variant",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
