# Generated by Django 4.1.4 on 2023-04-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0094_remove_productvariant_is_featured_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_sub_variant",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="product_sub_variant",
            name="quantity",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant_color",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
