# Generated by Django 4.1.4 on 2023-04-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0095_remove_product_sub_variant_is_featured_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product_Sub_Variant",
        ),
    ]
