# Generated by Django 4.1.4 on 2023-04-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0096_delete_product_sub_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="variant_color",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="variant_price",
        ),
    ]
