# Generated by Django 4.1.4 on 2023-04-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0097_remove_productvariant_variant_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_SubVariant",
            fields=[
                ("sub_variant_id", models.AutoField(primary_key=True, serialize=False)),
                ("color", models.CharField(max_length=10)),
                ("price", models.FloatField()),
                ("variant_quantity", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name="products",
            old_name="price",
            new_name="base_price",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="size",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="variant_quantity",
        ),
        migrations.AddField(
            model_name="products",
            name="total_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant_type",
            field=models.CharField(default=32, max_length=15),
        ),
    ]
