# Generated by Django 4.1.4 on 2023-04-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0099_product_color_delete_product_subvariant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="variant_price_add",
            field=models.IntegerField(default=0),
        ),
    ]
