# Generated by Django 4.1.4 on 2023-04-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0100_productvariant_variant_price_add"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_color",
            name="color_name",
            field=models.CharField(default="Black", max_length=10),
        ),
        migrations.AddField(
            model_name="product_color",
            name="price_change_on_color",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product_color",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.products",
            ),
        ),
    ]
