# Generated by Django 4.1.4 on 2023-04-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0102_product_color_product_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_color",
            name="product",
        ),
    ]
