# Generated by Django 4.1.4 on 2023-04-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0103_remove_product_color_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product_color",
            old_name="price_change_on_color",
            new_name="price_increase",
        ),
        migrations.AddField(
            model_name="product_color",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
