# Generated by Django 4.1.4 on 2023-04-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "category",
            "0104_rename_price_change_on_color_product_color_price_increase_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_color",
            name="color_name",
            field=models.CharField(default="Black", max_length=10, unique=True),
        ),
    ]
