# Generated by Django 4.1.4 on 2023-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0106_alter_product_color_color_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="variant_color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="Product_Color",
        ),
    ]
