# Generated by Django 4.1.4 on 2023-04-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0109_variant_color_delete_product_color"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Variant_Color",
            new_name="Product_Color",
        ),
    ]
