# Generated by Django 4.1.4 on 2023-04-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0110_rename_variant_color_product_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="price_after_offer",
            field=models.FloatField(default=0),
        ),
    ]
