# Generated by Django 4.1.4 on 2023-04-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0111_products_price_after_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="is_base_model",
            field=models.BooleanField(default=False),
        ),
    ]
