# Generated by Django 4.1.4 on 2023-04-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0113_product_color_is_base_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="variant_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
