# Generated by Django 4.1.4 on 2023-04-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0115_remove_productvariant_product_products_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="variant",
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
