# Generated by Django 4.1.4 on 2023-04-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0015_delete_cart"),
        ("category", "0116_alter_products_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="orderItem",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name_plural": "Products"},
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="Products",
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
