# Generated by Django 4.1.4 on 2023-04-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "category",
            "0117_remove_products_product_type_remove_wallet_orderitem_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "product_id",
                    models.AutoField(default=1, primary_key=True, serialize=False),
                ),
                ("product_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="products")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available", models.BooleanField(default=True)),
                ("quantity", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("os", models.CharField(blank=True, max_length=50)),
                ("display", models.CharField(blank=True, max_length=50)),
                ("storage", models.CharField(blank=True, max_length=50)),
                ("camera", models.CharField(blank=True, max_length=50)),
                ("battery", models.CharField(blank=True, max_length=50)),
                ("os_version", models.CharField(blank=True, max_length=50)),
                ("case_material", models.CharField(blank=True, max_length=50)),
                ("band_material", models.CharField(blank=True, max_length=50)),
                ("water_resistance", models.CharField(blank=True, max_length=50)),
                ("size", models.CharField(blank=True, max_length=50)),
                ("compatibility", models.CharField(blank=True, max_length=50)),
                ("battery_life", models.CharField(blank=True, max_length=50)),
                ("noise_cancellation", models.BooleanField(default=False)),
                ("wireless_charging", models.BooleanField(default=False)),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.producttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products",
            },
        ),
    ]
