# Generated by Django 4.1.4 on 2023-04-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0119_variant_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Variant",
        ),
    ]
