# Generated by Django 4.1.4 on 2023-04-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0121_variant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="image",
            new_name="main_image",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="quantity",
            new_name="total_quantity",
        ),
    ]
