# Generated by Django 4.1.4 on 2023-04-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0122_rename_image_products_main_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variant",
            old_name="name",
            new_name="variant_name",
        ),
    ]
