# Generated by Django 4.1.4 on 2023-04-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0123_rename_name_variant_variant_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="color",
            old_name="name",
            new_name="color_name",
        ),
    ]
