# Generated by Django 4.1.4 on 2023-04-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0124_rename_name_color_color_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Color",
            new_name="Product_Color",
        ),
        migrations.RenameModel(
            old_name="Variant",
            new_name="ProductVariant",
        ),
    ]
