# Generated by Django 4.1.4 on 2023-04-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0125_rename_color_product_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_color",
            name="product_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_colors",
                to="category.productvariant",
            ),
        ),
    ]
