# Generated by Django 4.1.4 on 2023-04-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0126_product_color_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_color",
            name="color_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
