# Generated by Django 4.1.4 on 2023-04-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0128_remove_product_color_product_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="storage",
        ),
    ]
