# Generated by Django 4.1.4 on 2023-04-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0129_remove_products_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_color",
            name="is_base_color",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_base_variant",
            field=models.BooleanField(default=False),
        ),
    ]
