# Generated by Django 4.1.4 on 2023-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0131_variantcolor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_color",
            name="color_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
