# Generated by Django 4.1.4 on 2023-04-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0132_alter_product_color_color_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="second_image",
            field=models.ImageField(blank=True, upload_to="products"),
        ),
        migrations.AddField(
            model_name="products",
            name="third_image",
            field=models.ImageField(blank=True, upload_to="products"),
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
