# Generated by Django 4.1.4 on 2023-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0134_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="price_after_offer",
            field=models.FloatField(default=0),
        ),
    ]
