# Generated by Django 4.1.4 on 2023-04-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0135_products_price_after_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="total_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
