# Generated by Django 4.1.4 on 2022-12-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_billingaddress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billingaddress",
            old_name="user_id",
            new_name="user",
        ),
    ]
